"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['webmapper.py']
DATA_FILES = [('',['js']),
              ('',['includes']),
              ('',['css']),
              ('',['images']),
              ('',['html'])
              ]

OPTIONS = {'argv_emulation': True,
           'iconfile': 'images/libmapper.icns',
           'packages': ['netifaces', 'libmapper'],
           'frameworks': ['/usr/local/lib/python3.10/site-packages/libmapper/libmapper.dylib',
                          '/usr/local/lib/python3.10/site-packages/libmapper/liblo.dylib']
}

setup(
    name='WebMapper',
    version='2.3',
    description='Graphical interface for the libmapper distributed mapping graph',
    author='Joseph Malloch, Aaron Krajeski, Jon Wilansky, Stephen Sinclair,  Travis West, Brady Boettcher, Johnty Wang, Matt Peachey, Mathias Bredholt, Christian Frisson, and Marcello Giordano',
    author_email='jmalloch@dal.ca',
    url='http://libmapper.org',
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
